### PR TITLE
Add Dockerfile to build a container for this game

### PR DESCRIPTION
**Pull request by kevinastone**
The `Dockerfile` builds the dist folder and then serves the files with an nginx container.

This lets you run this app/game with `docker run -p 3000:80 <image>`

### CODE REVIEW

**Comment by kevinastone** [comment]
And just an FYI That your peer-dependencies are currently misaligned to the new npm resolution process.  I worked around this by using `--legacy-peer-deps` in the Dockerfile.  Otherwise, `npm install` fails (hence the Netlify deploy failure on this PR).

**Comment by TN1ck** [comment]
@kevinastone Thanks for this, sorry I didn't notice this PR. I'll merge this and then improve upon it to get rid of the npm peer dependency issue.

**Comment by kevinastone** [comment]
I have a GitHub action running on my fork to build the docker image and publish to the GHCR.  Let me know if you'd like a pull-request to add this upstream as well.

https://github.com/kevinastone/super-sudoku/commit/2c05558c0dadc7c9a8dd035fc99d54bcdc357f18

**Comment by TN1ck** [comment]
Oh cool @kevinastone! Will have a look. I improved upon the image a bit (upgrade the node version and used slim and made the npm install a separate layer so if anybody wants to develop with this, it's faster to do so).

**Comment by TN1ck** [comment]
@kevinastone Added it, the images are available at https://github.com/tn1ck/super-sudoku/pkgs/container/super-sudoku

**Pull request merged**
